extends: "airbnb"
parser: "babel-eslint"
env:
  browser: true
  jasmine: true
  es6: true
  node: true
globals:
  jest: true
rules:
  global-require: 0
  no-param-reassign: 0
  no-mixed-operators: 0
  no-constant-condition: 0
  react/require-default-props: 0
  react/jsx-filename-extension: [2, { "extensions": [".js", ".jsx"] }]